### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by makersmelx** [makersmelx/CrawlBot#1]
- [ ] Support saving pics in the server

- [ ] Move all the variables to a json

- [ ] Reframe

**Comment by makersmelx** [comment]
- [ ] Calculate probability

- [ ] Support abstract language
